### ISSUE TITLE
Homogenise interface for DataContainer objects

### ISSUE THREAD

**Issue by psomhorst** [EIT-ALIVE/eitprocessing#279] opened 2024-07-17 07:46 UTC

**Comment by psomhorst** [comment] 2024-07-17 07:47
See discussion in #275.

**Comment by DaniBodor** [comment] 2024-07-17 07:51
Duplicate of #278 (I just created the same issue 😉). I'll close this one, as I've already moved the comments into the other issue

**Closed by DaniBodor** 2024-07-17 07:51 UTC
